/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'imageId' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const Variant = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'inventory' : IDL.Nat,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : IDL.Text,
  'price' : IDL.Nat,
  'material' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'placed' : IDL.Null,
  'fulfilled' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'delivered' : IDL.Null,
  'returned' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'variantId' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'product' : Product,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'statusHistory' : IDL.Vec(IDL.Tuple(OrderStatus, Time)),
  'deliveryMethod' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'contactEmail' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const ReturnRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'reason' : IDL.Text,
});
export const Analytics = IDL.Record({
  'revenueTotal' : IDL.Nat,
  'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'ordersCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'shippingAddress' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'variantId' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'completeRefund' : IDL.Func([IDL.Text], [], []),
  'createBundle' : IDL.Func([Bundle], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'createVariant' : IDL.Func([Variant], [], []),
  'deleteBundle' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteVariant' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getBundle' : IDL.Func([IDL.Text], [Bundle], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getRecommendations' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
  'getSortedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVariant' : IDL.Func([IDL.Text], [Variant], ['query']),
  'initiateReturn' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'processReturnRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'trackProductView' : IDL.Func([IDL.Text], [], []),
  'updateBundle' : IDL.Func([Bundle], [], []),
  'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateVariant' : IDL.Func([Variant], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'imageId' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const Variant = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'inventory' : IDL.Nat,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : IDL.Text,
    'price' : IDL.Nat,
    'material' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'placed' : IDL.Null,
    'fulfilled' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'delivered' : IDL.Null,
    'returned' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'variantId' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'product' : Product,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'statusHistory' : IDL.Vec(IDL.Tuple(OrderStatus, Time)),
    'deliveryMethod' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'contactEmail' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const ReturnRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'revenueTotal' : IDL.Nat,
    'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'ordersCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'shippingAddress' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({
    'variantId' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'product' : Product,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'completeRefund' : IDL.Func([IDL.Text], [], []),
    'createBundle' : IDL.Func([Bundle], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'createVariant' : IDL.Func([Variant], [], []),
    'deleteBundle' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteVariant' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getBundle' : IDL.Func([IDL.Text], [Bundle], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
    'getSortedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVariant' : IDL.Func([IDL.Text], [Variant], ['query']),
    'initiateReturn' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Text],
        [],
      ),
    'processReturnRequest' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'trackProductView' : IDL.Func([IDL.Text], [], []),
    'updateBundle' : IDL.Func([Bundle], [], []),
    'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateVariant' : IDL.Func([Variant], [], []),
  });
};

export const init = ({ IDL }) => { return []; };