/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'revenueTotal' : bigint,
  'topProducts' : Array<[string, bigint]>,
  'ordersCount' : bigint,
}
export interface Bundle {
  'id' : string,
  'productIds' : Array<string>,
  'name' : string,
  'description' : string,
  'imageId' : [] | [string],
  'price' : bigint,
}
export interface CartItem {
  'variantId' : [] | [string],
  'quantity' : bigint,
  'product' : Product,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'createdAt' : Time,
  'statusHistory' : Array<[OrderStatus, Time]>,
  'deliveryMethod' : string,
  'totalAmount' : bigint,
  'contactEmail' : string,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
  'contactPhone' : [] | [string],
}
export interface OrderItem {
  'variantId' : [] | [string],
  'quantity' : bigint,
  'price' : bigint,
  'product' : Product,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'placed' : null } |
  { 'fulfilled' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'delivered' : null } |
  { 'returned' : null };
export interface Product {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'brand' : [] | [string],
  'imageId' : [] | [string],
  'price' : bigint,
}
export interface ReturnRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'customer' : Principal,
  'createdAt' : Time,
  'orderId' : string,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'shippingAddress' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variant {
  'id' : string,
  'sku' : string,
  'inventory' : bigint,
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : string,
  'price' : bigint,
  'material' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'completeRefund' : ActorMethod<[string], undefined>,
  'createBundle' : ActorMethod<[Bundle], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createVariant' : ActorMethod<[Variant], undefined>,
  'deleteBundle' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteVariant' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getBundle' : ActorMethod<[string], Bundle>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getRecommendations' : ActorMethod<[], Array<Product>>,
  'getReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getSortedProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVariant' : ActorMethod<[string], Variant>,
  'initiateReturn' : ActorMethod<[string, string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, [] | [string], string], string>,
  'processReturnRequest' : ActorMethod<[string, boolean], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'trackProductView' : ActorMethod<[string], undefined>,
  'updateBundle' : ActorMethod<[Bundle], undefined>,
  'updateCartItem' : ActorMethod<[string, bigint], undefined>,
  'updateInventory' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateVariant' : ActorMethod<[Variant], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];