/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    variantId?: string;
    quantity: bigint;
    price: bigint;
    product: Product;
}
export interface Bundle {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    imageId?: string;
    price: bigint;
}
export interface Variant {
    id: string;
    sku: string;
    inventory: bigint;
    color?: string;
    size?: string;
    productId: string;
    price: bigint;
    material?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReturnRequest {
    id: string;
    status: Variant_pending_completed_approved_rejected;
    customer: Principal;
    createdAt: Time;
    orderId: string;
    reason: string;
}
export interface Order {
    id: string;
    status: OrderStatus;
    customer: Principal;
    createdAt: Time;
    statusHistory: Array<[OrderStatus, Time]>;
    deliveryMethod: string;
    totalAmount: bigint;
    contactEmail: string;
    shippingAddress: string;
    items: Array<OrderItem>;
    contactPhone?: string;
}
export interface Analytics {
    revenueTotal: bigint;
    topProducts: Array<[string, bigint]>;
    ordersCount: bigint;
}
export interface CartItem {
    variantId?: string;
    quantity: bigint;
    product: Product;
}
export interface Product {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    category: string;
    brand?: string;
    imageId?: string;
    price: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    shippingAddress?: string;
    phone?: string;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    placed = "placed",
    fulfilled = "fulfilled",
    paid = "paid",
    refunded = "refunded",
    delivered = "delivered",
    returned = "returned"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_approved_rejected {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToCart(productId: string, quantity: bigint, variantId: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    completeRefund(returnId: string): Promise<void>;
    createBundle(bundle: Bundle): Promise<void>;
    createProduct(product: Product): Promise<void>;
    createVariant(variant: Variant): Promise<void>;
    deleteBundle(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteVariant(id: string): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllReturnRequests(): Promise<Array<ReturnRequest>>;
    getAnalytics(): Promise<Analytics>;
    getBundle(id: string): Promise<Bundle>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getOrder(orderId: string): Promise<Order>;
    getOrderHistory(): Promise<Array<Order>>;
    getProduct(id: string): Promise<Product>;
    getProductsByBrand(brand: string): Promise<Array<Product>>;
    getProductsByCategory(category: string): Promise<Array<Product>>;
    getRecommendations(): Promise<Array<Product>>;
    getReturnRequests(): Promise<Array<ReturnRequest>>;
    getSortedProducts(): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVariant(id: string): Promise<Variant>;
    initiateReturn(orderId: string, reason: string): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(shippingAddress: string, contactEmail: string, contactPhone: string | null, deliveryMethod: string): Promise<string>;
    processReturnRequest(returnId: string, approved: boolean): Promise<void>;
    removeFromCart(productId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    trackProductView(productId: string): Promise<void>;
    updateBundle(bundle: Bundle): Promise<void>;
    updateCartItem(productId: string, quantity: bigint): Promise<void>;
    updateInventory(productId: string, newInventory: bigint): Promise<void>;
    updateOrderStatus(orderId: string, newStatus: OrderStatus): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateVariant(variant: Variant): Promise<void>;
}
import type { Bundle as _Bundle, CartItem as _CartItem, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Product as _Product, ReturnRequest as _ReturnRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Variant as _Variant, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToCart(arg0: string, arg1: bigint, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async completeRefund(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRefund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRefund(arg0);
            return result;
        }
    }
    async createBundle(arg0: Bundle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBundle(to_candid_Bundle_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBundle(to_candid_Bundle_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVariant(arg0: Variant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVariant(to_candid_Variant_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVariant(to_candid_Variant_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBundle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBundle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBundle(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteVariant(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVariant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVariant(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReturnRequests(): Promise<Array<ReturnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReturnRequests();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReturnRequests();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBundle(arg0: string): Promise<Bundle> {
        if (this.processError) {
            try {
                const result = await this.actor.getBundle(arg0);
                return from_candid_Bundle_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBundle(arg0);
            return from_candid_Bundle_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistory(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistory();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistory();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByBrand(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByBrand(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByBrand(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReturnRequests(): Promise<Array<ReturnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnRequests();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnRequests();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedProducts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedProducts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVariant(arg0: string): Promise<Variant> {
        if (this.processError) {
            try {
                const result = await this.actor.getVariant(arg0);
                return from_candid_Variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVariant(arg0);
            return from_candid_Variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateReturn(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateReturn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateReturn(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async processReturnRequest(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processReturnRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processReturnRequest(arg0, arg1);
            return result;
        }
    }
    async removeFromCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackProductView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackProductView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackProductView(arg0);
            return result;
        }
    }
    async updateBundle(arg0: Bundle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBundle(to_candid_Bundle_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBundle(to_candid_Bundle_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCartItem(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return result;
        }
    }
    async updateInventory(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVariant(arg0: Variant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVariant(to_candid_Variant_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVariant(to_candid_Variant_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Bundle_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bundle): Bundle {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_CartItem_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnRequest): ReturnRequest {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Variant): Variant {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    customer: Principal;
    createdAt: _Time;
    statusHistory: Array<[_OrderStatus, _Time]>;
    deliveryMethod: string;
    totalAmount: bigint;
    contactEmail: string;
    shippingAddress: string;
    items: Array<_OrderItem>;
    contactPhone: [] | [string];
}): {
    id: string;
    status: OrderStatus;
    customer: Principal;
    createdAt: Time;
    statusHistory: Array<[OrderStatus, Time]>;
    deliveryMethod: string;
    totalAmount: bigint;
    contactEmail: string;
    shippingAddress: string;
    items: Array<OrderItem>;
    contactPhone?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        createdAt: value.createdAt,
        statusHistory: from_candid_vec_n22(_uploadFile, _downloadFile, value.statusHistory),
        deliveryMethod: value.deliveryMethod,
        totalAmount: value.totalAmount,
        contactEmail: value.contactEmail,
        shippingAddress: value.shippingAddress,
        items: from_candid_vec_n24(_uploadFile, _downloadFile, value.items),
        contactPhone: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.contactPhone))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    variantId: [] | [string];
    quantity: bigint;
    price: bigint;
    product: _Product;
}): {
    variantId?: string;
    quantity: bigint;
    price: bigint;
    product: Product;
} {
    return {
        variantId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.variantId)),
        quantity: value.quantity,
        price: value.price,
        product: from_candid_Product_n28(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    category: string;
    brand: [] | [string];
    imageId: [] | [string];
    price: bigint;
}): {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    category: string;
    brand?: string;
    imageId?: string;
    price: bigint;
} {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        category: value.category,
        brand: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.brand)),
        imageId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.imageId)),
        price: value.price
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    customer: Principal;
    createdAt: _Time;
    orderId: string;
    reason: string;
}): {
    id: string;
    status: Variant_pending_completed_approved_rejected;
    customer: Principal;
    createdAt: Time;
    orderId: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        createdAt: value.createdAt,
        orderId: value.orderId,
        reason: value.reason
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    imageId: [] | [string];
    price: bigint;
}): {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    imageId?: string;
    price: bigint;
} {
    return {
        id: value.id,
        productIds: value.productIds,
        name: value.name,
        description: value.description,
        imageId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.imageId)),
        price: value.price
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    shippingAddress: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    shippingAddress?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.email)),
        shippingAddress: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.shippingAddress)),
        phone: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    variantId: [] | [string];
    quantity: bigint;
    product: _Product;
}): {
    variantId?: string;
    quantity: bigint;
    product: Product;
} {
    return {
        variantId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.variantId)),
        quantity: value.quantity,
        product: from_candid_Product_n28(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    inventory: bigint;
    color: [] | [string];
    size: [] | [string];
    productId: string;
    price: bigint;
    material: [] | [string];
}): {
    id: string;
    sku: string;
    inventory: bigint;
    color?: string;
    size?: string;
    productId: string;
    price: bigint;
    material?: string;
} {
    return {
        id: value.id,
        sku: value.sku,
        inventory: value.inventory,
        color: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.color)),
        size: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.size)),
        productId: value.productId,
        price: value.price,
        material: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.material))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_OrderStatus, _Time]): [OrderStatus, Time] {
    return [
        from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    fulfilled: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    delivered: null;
} | {
    returned: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "placed" in value ? OrderStatus.placed : "fulfilled" in value ? OrderStatus.fulfilled : "paid" in value ? OrderStatus.paid : "refunded" in value ? OrderStatus.refunded : "delivered" in value ? OrderStatus.delivered : "returned" in value ? OrderStatus.returned : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_completed_approved_rejected {
    return "pending" in value ? Variant_pending_completed_approved_rejected.pending : "completed" in value ? Variant_pending_completed_approved_rejected.completed : "approved" in value ? Variant_pending_completed_approved_rejected.approved : "rejected" in value ? Variant_pending_completed_approved_rejected.rejected : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_OrderStatus, _Time]>): Array<[OrderStatus, Time]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReturnRequest>): Array<ReturnRequest> {
    return value.map((x)=>from_candid_ReturnRequest_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n43(_uploadFile, _downloadFile, x));
}
function to_candid_Bundle_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bundle): _Bundle {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant): _Variant {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    imageId?: string;
    price: bigint;
}): {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    imageId: [] | [string];
    price: bigint;
} {
    return {
        id: value.id,
        productIds: value.productIds,
        name: value.name,
        description: value.description,
        imageId: value.imageId ? candid_some(value.imageId) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    category: string;
    brand?: string;
    imageId?: string;
    price: bigint;
}): {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    category: string;
    brand: [] | [string];
    imageId: [] | [string];
    price: bigint;
} {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        category: value.category,
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        imageId: value.imageId ? candid_some(value.imageId) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    inventory: bigint;
    color?: string;
    size?: string;
    productId: string;
    price: bigint;
    material?: string;
}): {
    id: string;
    sku: string;
    inventory: bigint;
    color: [] | [string];
    size: [] | [string];
    productId: string;
    price: bigint;
    material: [] | [string];
} {
    return {
        id: value.id,
        sku: value.sku,
        inventory: value.inventory,
        color: value.color ? candid_some(value.color) : candid_none(),
        size: value.size ? candid_some(value.size) : candid_none(),
        productId: value.productId,
        price: value.price,
        material: value.material ? candid_some(value.material) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    shippingAddress?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    shippingAddress: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        shippingAddress: value.shippingAddress ? candid_some(value.shippingAddress) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    fulfilled: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    delivered: null;
} | {
    returned: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.fulfilled ? {
        fulfilled: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.refunded ? {
        refunded: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.returned ? {
        returned: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
